# Generated by Django 6.0.2 on 2026-02-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='板块图片')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.CharField(max_length=300, verbose_name='简介')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='跳转链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '介绍板块',
                'verbose_name_plural': '介绍板块',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePagePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='图片链接')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.CharField(max_length=500, verbose_name='介绍')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '主页轮播图',
                'verbose_name_plural': '主页轮播图',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='配图')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '介绍文章',
                'verbose_name_plural': '介绍文章',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='标识')),
                ('label', models.CharField(max_length=50, verbose_name='显示文字')),
                ('path', models.CharField(max_length=200, verbose_name='路径')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '导航项',
                'verbose_name_plural': '导航项',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('intro', models.CharField(max_length=500, verbose_name='简介')),
                ('content', models.TextField(verbose_name='正文')),
                ('prim_pic', models.URLField(max_length=500, verbose_name='主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.news')),
            ],
            options={
                'verbose_name': '新闻配图',
                'verbose_name_plural': '新闻配图',
                'ordering': ['sort_order'],
            },
        ),
    ]
