# Generated by Django 6.0.2 on 2026-02-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_news_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
