"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 从项目根目录加载环境变量：优先 .env，不存在则用 .env.example（便于本地直接用 example 调试）
from dotenv import load_dotenv
_env_file = BASE_DIR / '.env'
_env_example = BASE_DIR / '.env.example'
if _env_file.exists():
    load_dotenv(_env_file)
elif _env_example.exists():
    load_dotenv(_env_example)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-$$n0e2xvq_0o#e^rtb5dhhcdtg4&6g!)n@9bkq$^0xrf@x9j5y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# ALLOWED_HOSTS: 本地用 localhost；Railway 部署时必须包含域名（Railway 会设置 PORT）
_allowed = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
if os.environ.get('PORT'):
    _allowed.append('.railway.app')
ALLOWED_HOSTS = list(dict.fromkeys(_allowed))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'config.health_middleware.HealthEarlyResponseMiddleware',  # 最先：/ 与 /api/health/ 直接 200，不碰 DB
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 优先 DATABASE_URL（Railway PostgreSQL 等）；否则 USE_MYSQL=1 用 MySQL；否则 SQLite（容器重启会丢数据）

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('USE_MYSQL') == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'bassc_db'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CORS - 允许 React 前端跨域请求（含 Dashboard）。
# 部署到 Railway 时：除 CORS_ALLOWED_ORIGINS 外，允许任意 https://*.railway.app，避免前端域名带 -7145 等后缀被拒。
_default_origins = [
    'http://localhost:5173', 'http://localhost:5174', 'http://localhost:5175',
    'http://127.0.0.1:5173', 'http://127.0.0.1:5174', 'http://127.0.0.1:5175',
]
_raw = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
CORS_ALLOWED_ORIGINS = [o.strip() for o in _raw.split(',') if o.strip()] if _raw else _default_origins
# Railway 上允许所有 *.railway.app 前端来源（OPTIONS 预检会带上正确 Allow-Origin）
if os.environ.get('PORT'):
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^https://[a-z0-9-]+\.up\.railway\.app$']
CORS_ALLOW_CREDENTIALS = True

# Railway Bucket（S3 兼容）- 图片上传
RAILWAY_BUCKET_ACCESS_KEY = os.environ.get('RAILWAY_BUCKET_ACCESS_KEY', '')
RAILWAY_BUCKET_SECRET_KEY = os.environ.get('RAILWAY_BUCKET_SECRET_KEY', '')
RAILWAY_BUCKET_ENDPOINT = os.environ.get('RAILWAY_BUCKET_ENDPOINT', 'https://t3.storageapi.dev')
RAILWAY_BUCKET_NAME = os.environ.get('RAILWAY_BUCKET_NAME', '')
# 公网访问基础 URL（若存储为私有，可改为后端代理或预签名）
RAILWAY_BUCKET_PUBLIC_BASE = os.environ.get(
    'RAILWAY_BUCKET_PUBLIC_BASE',
    None,
)

# 素材展示逻辑：无存储图片时使用的默认图（轮播/board/news/introduction 等统一用此占位）
DEFAULT_PLACEHOLDER_IMAGE = os.environ.get(
    'DEFAULT_PLACEHOLDER_IMAGE',
    '/static/default-placeholder.png',
)

# Django REST Framework - 使用 Token 认证，避免跨域 CSRF 问题
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'api.parsers.PlainTextJSONParser',  # 支持前端发 text/plain;charset=UTF-8 的 JSON
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
